---
provisioner:
  name: chef_solo
  chef_git_sha: <%= %x(git rev-parse HEAD) %>
  chef_git_url: "github.com/opscode/chef"
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver_plugin: vagrant

suites:
  - name: default
    run_list:
      - recipe[example::default]
    attributes:
