---
provisioner:
  name: chef_solo
  solo_rb:
    cookbook_path: "./cookbooks"
  github: "opscode/chef"
  branch: <%= %x(git rev-parse HEAD) %>
  require_chef_omnibus: true

platforms:
  - name: ubuntu-12.04
    driver_plugin: vagrant

suites:
  - name: webserver
    run_list:
      - recipe[apt::default]
      - recipe[webserver::default]
    attributes:
